### ISSUE TITLE
You can't distribute Mojang's code.

### ISSUE THREAD

**Issue by Igrium** [Eisenwave/eisen-nbt#2]
I'm not sure of the best way to let you know of this, but decompiling, de-obfuscating and modifying Minecraft source code like you say in your readme.md is illegal if you intend to redistribute it here like you are. Furthermore, this makes it so that anyone who uses this API is also breaking the law, so I would HIGHLY recommend fixing before Mojang finds it.

(If you wrote the rest of the code yourself, just analyze and come to understand Mojang's code, and then write your own version..)

**Comment by eisenwave** [comment]
Actually all of the code was written entirely by me, none of it is decompiled and copied.
So this is merely the result of reverse-engineering.
